"""
Email Notifier Module
ส่งอีเมลแจ้งเตือนผลการวิเคราะห์ Trading Bot
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime


class EmailNotifier:
    """ส่งอีเมลแจ้งเตือนผลการวิเคราะห์"""

    def __init__(self, sender_email, sender_password, recipient_email):
        self.sender_email = sender_email
        self.sender_password = sender_password
        self.recipient_email = recipient_email
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587

    def create_html_email(self, console_output, mode):
        """สร้าง HTML email จาก console output"""

        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # แปลง console output เป็น HTML
        html_content = self._convert_to_html(console_output)

        html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #1a1a2e;
            color: #eee;
            padding: 20px;
            margin: 0;
        }}
        .container {{
            max-width: 800px;
            margin: 0 auto;
            background-color: #16213e;
            border-radius: 15px;
            padding: 30px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.5);
        }}
        .header {{
            text-align: center;
            padding: 20px 0;
            border-bottom: 2px solid #e94560;
            margin-bottom: 25px;
        }}
        .header h1 {{
            color: #e94560;
            margin: 0;
            font-size: 28px;
        }}
        .header p {{
            color: #888;
            margin: 10px 0 0;
        }}
        .signal-box {{
            padding: 20px;
            border-radius: 10px;
            margin: 20px 0;
            text-align: center;
        }}
        .signal-long {{
            background: linear-gradient(135deg, #0f3443, #34e89e20);
            border: 2px solid #34e89e;
        }}
        .signal-short {{
            background: linear-gradient(135deg, #3d0f0f, #e9344020);
            border: 2px solid #e94560;
        }}
        .signal-wait {{
            background: linear-gradient(135deg, #2d2d0f, #e9e93420);
            border: 2px solid #e9e934;
        }}
        .content {{
            background-color: #0f0f23;
            border-radius: 10px;
            padding: 20px;
            font-family: 'Courier New', monospace;
            font-size: 13px;
            line-height: 1.6;
            white-space: pre-wrap;
            overflow-x: auto;
        }}
        .footer {{
            text-align: center;
            margin-top: 25px;
            padding-top: 20px;
            border-top: 1px solid #333;
            color: #666;
            font-size: 12px;
        }}
        .emoji {{
            font-size: 1.1em;
        }}
        .green {{ color: #34e89e; }}
        .red {{ color: #e94560; }}
        .yellow {{ color: #ffd700; }}
        .blue {{ color: #4dabf7; }}
        .highlight {{
            background-color: #e9456020;
            padding: 2px 8px;
            border-radius: 4px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔥 Crypto Trading Bot v2.0 🔥</h1>
            <p>Analysis Report - {now}</p>
            <p>Mode: {mode.upper()}</p>
        </div>

        <div class="content">
{html_content}
        </div>

        <div class="footer">
            <p>⚠️ This is an automated trading analysis. Always do your own research.</p>
            <p>Generated by Crypto Trading Bot v2.0</p>
        </div>
    </div>
</body>
</html>
"""
        return html

    def _convert_to_html(self, text):
        """แปลง console text เป็น HTML พร้อม styling"""
        import html as html_lib

        # Escape HTML characters
        text = html_lib.escape(text)

        # แทนที่สีและ styling
        replacements = [
            # Signal highlights
            ("✅", '<span class="green">✅</span>'),
            ("❌", '<span class="red">❌</span>'),
            ("⚠️", '<span class="yellow">⚠️</span>'),
            ("🟢", '<span class="green">🟢</span>'),
            ("🔴", '<span class="red">🔴</span>'),
            ("🟡", '<span class="yellow">🟡</span>'),
            # Emojis styling
            ("📈", '<span class="green emoji">📈</span>'),
            ("📉", '<span class="red emoji">📉</span>'),
            ("💰", '<span class="yellow emoji">💰</span>'),
            ("🎯", '<span class="blue emoji">🎯</span>'),
            ("🛡️", '<span class="green emoji">🛡️</span>'),
            ("🎁", '<span class="yellow emoji">🎁</span>'),
            ("💵", '<span class="green emoji">💵</span>'),
            ("🔥", '<span class="red emoji">🔥</span>'),
            ("📊", '<span class="blue emoji">📊</span>'),
            ("💪", '<span class="green emoji">💪</span>'),
            ("🚀", '<span class="green emoji">🚀</span>'),
            ("🔻", '<span class="red emoji">🔻</span>'),
            ("☁️", '<span class="blue emoji">☁️</span>'),
            # Lines
            ("=" * 100, '<hr style="border-color: #e94560;">'),
            ("━" * 100, '<hr style="border-color: #4dabf7;">'),
        ]

        for old, new in replacements:
            text = text.replace(old, new)

        return text

    def send_email(self, console_output, mode):
        """ส่งอีเมล"""
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = f"🔥 Crypto Bot Alert - {mode.upper()} Analysis - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
            msg["From"] = self.sender_email
            msg["To"] = self.recipient_email

            # Text version
            text_part = MIMEText(console_output, "plain", "utf-8")
            msg.attach(text_part)

            # HTML version
            html_content = self.create_html_email(console_output, mode)
            html_part = MIMEText(html_content, "html", "utf-8")
            msg.attach(html_part)

            # ส่งอีเมล
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.sendmail(self.sender_email, self.recipient_email, msg.as_string())

            print("\n" + "=" * 50)
            print("📧 EMAIL SENT SUCCESSFULLY!")
            print(f"   To: {self.recipient_email}")
            print("=" * 50)
            return True

        except Exception as e:
            print(f"\n❌ Failed to send email: {e}")
            print("💡 Make sure you have set up App Password for Gmail")
            print("   1. Go to Google Account > Security")
            print("   2. Enable 2-Factor Authentication")
            print("   3. Create App Password for 'Mail'")
            return False
